### ISSUE TITLE
Show what client posts are created by

### ISSUE THREAD

**Issue by 33mhz** [matigo/nice_social#132]
Every other client I've seen shows this info on posts. It is very useful. As people become familiar with clients, they know that a post is being made from mobile or desktop, directly or crossposted, and other nuanced details. As well as, of course, the simplest mode of client discovery.

**Comment by matigo** [comment]
Yep. We have this already in the Conversation View as well as when viewing an Account Profile. Here's a quick screenshot showing the information:

![Showing Clients](https://cloud.githubusercontent.com/assets/3123903/8537318/5011116c-2498-11e5-813b-bb7618ca030d.png)

The decision was made to do it like this in order to save that one extra line on each post when viewing Nice on a narrower screen, such as a phone or tablet. Hope this answers your question :)
