### ISSUE TITLE
Split core.js into logical files

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#19]
I believe this would make development much more straightforward and it could still be bundled back into one file for the production version (although I don't think it's worth getting into task runners).

First thought was all the storage functions.

Thoughts?

**Comment by matigo** [comment]
This is something I've considered, but am loathe to ask people to run (seemingly) complex scripts to merge all the JavaScript files into a single cohesive file. Loading several JavaScript files would not be too much to ask, perhaps it would be better to go that route initially.

If the functions are going to be split out, then this may also be the most opportune time to move to a proper OOP model rather than simple procedural.

**Comment by mttmccb** [comment]
That's part of the motivation but I think it will ease the development by splitting things into manageable (logical, hopefully) chunks.

**Comment by matigo** [comment]
I believe this is being done as we go. Closing ticket for now, but let's try to keep the number of files to something manageable.
