### ISSUE TITLE
AutoComplete Auto-Entry on Tab

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#7]
There is no easy way to choose an AutoComplete name aside from tapping the one we want. Pressing Tab when the AutoComplete elements are open should put the first name in the list in the reply box.

**Comment by mttmccb** [comment]
When you say it should is that because it's not done yet? If I remember right TAB is a tricky key to get hold of cross-browser, maybe space or enter would work better? I'm at the stage I want to do the same thing in the [Dark Social](https://github.com/mttmccb/dark_social) I'm working with. At the moment I don't even have an autocomplete it simply reverts back to the previous known one if it doesn't exist.

I might go a fixing this one...

**Comment by matigo** [comment]
This issue has been resolved with @mttmccb's recent commit.

Thanks, Matt :)
