### ISSUE TITLE
Report Account as Spammer to NiceRank API

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#83]
In the account profile the option exists. Now it just needs to be coded.

Note: the account will not be immediately marked as a spammer but, instead, will be flagged for review. This should save me all sorts of time hunting down undesirable accounts.

**Comment by 0xMF** [comment]
this is a wonderful idea :+1:

**Comment by matigo** [comment]
This is set and ready to go with the next release.

**Comment by 33mhz** [comment]
I was going to say go a step further and send a PM to @jcn80 text: `report -u user_id` (and mark the returned channel read so your users don't have to), to have it submitted to be suspended from App.net--but if I understand correctly, NiceRank is a "what I don't like" ranking, not a "bad account" ranking.

**Comment by matigo** [comment]
NiceRank is a "this is not a human" ranking. Whether a person likes the content or not is inconsequential. That's what Mute/Block is for. When I see the account IDs I manually check the accounts to see what they're posting. If it's indeed all spam and no interaction, I'll mark the account as such. If it's just someone being a jerk, then their NR score is unchanged.

If an account is reported through @jcn80, are they "destroyed" later on?

**Comment by 33mhz** [comment]
I beg to differ. Point of contention: What is spam? You seem to define it by what you don't like; what you deem meaningless or "junky", from what I can tell. Junky generally being someone posting content from elsewhere. Not strictly, but generally.

Yeah, jcn80 picks up the report, checks it with the database and feeds it to be reviewed.

**Comment by matigo** [comment]
My apologies if the purpose of NiceRank is seen as contentious or as some sort of popularity contest. It's really none of these things. The tool is a means to identify accounts that are actively participating in the community, and ignoring the accounts that have no intentions of participating.

Here is a quick outline of how it works:
* Is the account marked a bot or feed? Leave it alone, it's good.
* Is the account marked human? Check it against the following criteria:
    * have any posts been made with whitelisted clients in the last 28 days?
    * what percentage of the posts contain a link to a non-ADN resource?
    * how many posts does the account make per day, and what is the spacing between them?
    * does the account post with a predictable timing pattern (a new post every 72 hours, etc.)
    * how many accounts does this account follow?
    * how many accounts follow this account?
    * how many conversations has this account participated in over the last 28 days?
    * (71 other checks)

People who pop in and out every so often but mostly cross-post via IFTTT/Buffer/TwitterFeed/etc. can still appear in the Filtered Global so long as there is some participation within a 28-day period. People who abandon the service but continue posting stuff from other places that always contain links will find themselves disappear from Filtered Global as their score drops below a certain threshold. That said, if other accounts on ADN are interacting with those cross-posted posts, the replied-to posts are *not* considered undesirable (because there was interaction, so the post was obviously desired).

If @ExampleAccount is incredibly active on Twitter and all of their Tweets are being cross-posted to ADN but they haven't made a post using a "human-powered" application in over 90 days, they'll have a NR somewhere between 0.25 and 1.75 (depending on how many links they're sharing, etc.). If you or I are interacting with many of those posts — even if @ExampleAccount never comes back to ADN — those interacted-with posts are considered part of a conversation and go towards boosting that person's NR score. With enough interaction, @ExampleAccount could reappear in Filtered Global, too ... even if the human never returns to ADN.

Nice has sweet nothing to do with blocking humans, and everything to do with making humans visible on the service. I never would have found half of the new accounts I've spoken to over the last 8 months without the algorithms that make the tool work. This is why I visually check accounts before marking an account as a spammer.

I hope this clarifies the purpose and intent of the NiceRank system.

**Comment by 33mhz** [comment]
I should clarify that I don't have a problem with NiceRank: I think it's pretty good at not filtering out people who are posting from App.net-specific clients, and it's a nice flavor to be able to pull up. It's just nothing to do with suspending accounts, nothing to do with ToS. "all spam and no interaction" is the sort of framing I'm skeptical of. You say it doesn't matter if someone doesn't like the content, but you've set it up for "community engagement", which is a very broad-stroke judgement of content. No big deal--lots of people agree, and it's a good resource.

And I'm still glad for you to hook your report button up to JCN, because it will still be useful data to help direct reviewing. Or you could have a Report button with two functions:
* Tos (against terms of service, like App.net's report button, for a wide range of offenses to send to JCN)
* Junk (or whatever you would say for NiceRank--"Nonparticipating" is rough wordage :smile_cat:)

Just pondering.

**Comment by 0xMF** [comment]
The interesting part of this discussion is ADN accounts should be allowed to post if they meet ToS but that doesn't mean they are required/forced to be read if, say, some like me doesn't want to read them. As of now, I cannot use Global - a service I pay for because free-tier clients have swamped it with spam. I would've liked a simple, reasonably effective, and automated system to make a first pass at Global (similar to spam filters on mail Inboxes) which is what Nice does, so spammers can spam all they want but if nobody (or dead accounts) read them then they are likely to spot, which anecdotally I seen to happen.

I know what I said seems obvious but at times the obvious needs to be said :pensive:

**Comment by 33mhz** [comment]
@0xMF It's more than a spam filter.
